version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: node:4.8.2

    steps:
      - checkout
      - restore_cache:
          key: webpack-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: |
            yarn
            yarn link || true && yarn link webpack
      - run:
          name: run tests
          command: |
            node -v
            yarn --version
            yarn run circleci:lint
            yarn run circleci:test
      - save_cache:
          key: webpack-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules
            - ~/.cache/yarn/
